version: '3.8'
services:

  app:
    build:
      args:
        user: khrustaliko
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/laravel
    volumes:
      - .:/var/www/laravel
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@db:3306/${DB_DATABASE}
    networks:
      - laravel
    links:
      - db

  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/laravel/public
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  db-data:
    driver: local

networks:
  laravel:
    driver: bridge
